# Generated by Django 2.1.2 on 2018-12-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=300)),
                ('movieId', models.CharField(max_length=300)),
                ('rate', models.CharField(max_length=300)),
                ('timestamp', models.CharField(max_length=300)),
            ],
        ),
    ]
