# Generated by Django 2.1.2 on 2018-12-05 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showMovies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieId',
            field=models.CharField(db_column='movieId', max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movieId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showMovies.movie'),
        ),
    ]
